export enum SOCKET_EVENTS {
    CREATE_ROOM = 'createRoom',
    JOIN_ROOM = 'joinRoom',
    SET_ROUND = 'setRound',
    SEND_ANSWER = 'sendAnswer',
    SUBMIT_SORTING = 'submitSorting',
    UPDATE_MASTER = 'updateMaster',
    PLAYER_JOIN = 'playerJoin',
    SET_LIST_TOPIC = 'setListTopic',
    JOIN_ROOM_ERROR = 'joinRoomError',
    FLIP_ANSWER = 'flipAnswer',
    PLAYER_LEFT = 'playerLeft',
    SET_NUMBER_ROUNDS = 'setNumberRounds',
    CHANGE_SORTING = 'changeSorting',
    SET_ALL_QUESTIONS = 'setAllQuestions',
}