export const QUESTIONS = [
  "What would you do with a million dollars?, From saving it all to pouring it down the drain",
  "What are your favorite vacation spots?, From staycation to traveling to the moon",
  "What are the worst movie endings?, From unsatisfying to ruining the entire film",
  "What's the best pizza topping?, From gross to necessary ingredient",
  "What's your favorite hobby?, From collecting stamps to extreme sports",
  "What's the best way to unwind?, From taking a bath to skydiving",
  "What's your favorite food?, From plain toast to exotic cuisine",
  "What's your favorite mode of transportation?, From walking to flying cars",
  "If you switched lives with a movie/tv-show character, who is it?, From I want my life back now to I can stay in this body forever",
  "Name a movie scene?, From meh to unforgettable",
  "Which movie do you choose for a movie night with your parents?, From unpleasant to great evening",
  "Name a present for your father., From awful to best present ever",
  "Your friend calls you in the middle of the night to pick her up. What is the reason?, From let me sleep to WTF???",
  "You wake up after a party night and can't remember anything. You call your friend, what is he/she telling you?, From not again to WTF???",
  "Your boss calls you on a day off. What is the reason?, From let me enjoy my day off to emergency meeting",
  "Your significant other surprises you with a date. What is the plan?, From lame to dream date",
  "Your neighbor knocks on your door early in the morning. What is the reason?, From let me sleep to emergency",
  "Your friend texts you to hang out. What is the plan?, From staying in to wild night out",
  "You receive an email from a long lost relative. What is the reason?, From just checking in to life changing news",
  "What's the best superpower?, From lame to life changing",
  "You read your mothers diary. What do you find out?, From lame to shocking",
  "You look through your partners' phone. What do you find there?, From happy together to divorce now",
  ]
